version: '3.3'

services:
  notebook:
    build: .
    image: sparsity-norm:${TAG:-latest}
    ports:
      - 8888:8888
    environment: &notebook_env
      # we can add envars here anything private should go in docker-compose.override.yml file
      # but with a stub here
      PROJECT_NAME: SparsityNorm
    entrypoint:
      - jupyter
      - lab
      - --allow-root
    volumes:
      - type: bind
        source: ./notebooks/
        target: /src/notebooks
      - type: bind
        source: ./python/
        target: /src/python

